INSERT INTO src_cmc.cmc_asset_map (
    cmc_id,
    symbol,
    name,
    slug,
    listing_status,
    is_active,
    rank_num,
    platform_name,
    platform_slug,
    platform_symbol,
    token_address,
    first_historical_data,
    last_historical_data,
    raw_response_id,
    fetched_at,
    updated_at
) VALUES (
    %s,
    %s,
    %s,
    %s,
    %s,
    %s,
    %s,
    %s,
    %s,
    %s,
    %s,
    %s::timestamptz,
    %s::timestamptz,
    %s,
    %s::timestamptz,
    NOW()
)
ON CONFLICT (cmc_id) DO UPDATE SET
    symbol = EXCLUDED.symbol,
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    listing_status = EXCLUDED.listing_status,
    is_active = EXCLUDED.is_active,
    rank_num = EXCLUDED.rank_num,
    platform_name = EXCLUDED.platform_name,
    platform_slug = EXCLUDED.platform_slug,
    platform_symbol = EXCLUDED.platform_symbol,
    token_address = EXCLUDED.token_address,
    first_historical_data = COALESCE(EXCLUDED.first_historical_data, src_cmc.cmc_asset_map.first_historical_data),
    last_historical_data = COALESCE(EXCLUDED.last_historical_data, src_cmc.cmc_asset_map.last_historical_data),
    raw_response_id = EXCLUDED.raw_response_id,
    fetched_at = EXCLUDED.fetched_at,
    updated_at = NOW();

